kind: pipeline
type: kubernetes
name: default

steps:
  - name: install_dependencies
    image: node:12
    commands:
      - npm ci
  - name: format
    image: node:12
    commands:
      - npm run prettier:check
    depends_on: [install_dependencies]
  - name: test_unit
    image: node:12
    commands:
      - npm run test:unit
    depends_on: [install_dependencies]
  - name: test_e2e
    image: cypress/base:12.1.0
    commands:
      - npm run cypress:install
      - npm run test:e2e:ci
    depends_on: [install_dependencies]
  - name: build
    image: node:12
    commands:
      - npm run build
    depends_on: [install_dependencies]
