kind: pipeline
type: kubernetes
name: general

steps:
  - name: install_dependencies
    image: node:12
    commands:
      - npm ci
  - name: format
    image: node:12
    commands:
      - npm run prettier:check
    depends_on: [install_dependencies]
  - name: test_e2e
    image: cypress/base:12.1.0
    commands:
      - npm run cypress:install
      - npm run test:e2e:ci
    depends_on: [install_dependencies]
  - name: build
    image: node:12
    commands:
      - npm run build
    depends_on: [install_dependencies]
  - name: deploy
    image: caprover/cli-caprover:latest
    commands:
      - npx caprover deploy -h $CAPROVER_DOMAIN -p $CAPROVER_PASSWORD -b ${DRONE_TAG} -a $CAPROVER_APPNAME
    environment:
      CAPROVER_DOMAIN:
        from_secret: CAPROVER_DOMAIN
      CAPROVER_APPNAME:
        from_secret: CAPROVER_APPNAME
      CAPROVER_PASSWORD:
        from_secret: CAPROVER_PASSWORD
    depends_on: [format, test_e2e, build]
    when:
      event: tag
